In [1]:
import psycopg2 as pg2 
import pandas as pd

In [2]:
data = pd.read_html('https://en.wikipedia.org/wiki/Programming_languages_used_in_most_popular_websites')

In [3]:
df = data[0]

In [4]:
df

,Websites,Popularity (unique visitors per month)[1],Front-end (Client-side),Back-end (Server-side),Database,Notes
0,Google[2],2800000000,"JavaScript, TypeScript","C, C++, Go,[3] Java, Python, Node","Bigtable,[4] MariaDB[5]",The most used search engine in the world.
1,Facebook,1120000000,"JavaScript, Typescript, Flow","Hack/HHVM, Python, C++, Java, Erlang, D,[6] Ha...","MariaDB, MySQL,[8] HBase, Cassandra[9]",The most visited social networking site.
2,YouTube,1100000000,"JavaScript, TypeScript","Python, C, C++, Java,[10] Go[11]","Vitess, BigTable, MariaDB[5][12]",The most popular video sharing site.
3,Yahoo,750000000,JavaScript,PHP,"PostgreSQL, HBase, Cassandra, MongoDB,[13]",NaN
4,Etsy,"516,000,000 (Total, not unique)[14]",JavaScript,PHP[15][16],"MySQL, Redis[17]",E-commerce website.
5,Amazon,"2,400,000,000[18]",JavaScript,"Java, C++, Perl[19]","DynamoDB, RDS/Aurora, Redshift[20]",The most used e-commerce site in the world.
6,Wikipedia,475000000,JavaScript,PHP,MariaDB[21],"A free online encyclopedia based on MediaWiki,..."
7,Fandom,"315,000,000[22]",JavaScript,PHP,MySQL,Wiki hosting service.
8,Twitter,290000000,JavaScript,"C++, Java,[23] Scala,[24] Ruby (Ruby On Rails)",MySQL[25],Popular social network.
9,Bing,285000000,JavaScript,"C++, C#","Microsoft SQL Server, Cosmos DB",Search engine from Microsoft.
10,eBay,285000000,JavaScript,"Java,[26] JavaScript,[27] Scala[28]",Oracle Database,Online auction house.
11,MSN,280000000,JavaScript,C# (ASP.NET),Microsoft SQL Server,"An email client, for simple use. Previously kn..."
12,LinkedIn,260000000,JavaScript,"Java, JavaScript,[29] Scala",Venice[30][31],World's largest professional network.
13,Pinterest,250000000,JavaScript,"Python (Django),[32] Erlang, Elixir[33]","MySQL, Redis[34]",Search engine for ideas.
14,WordPress.com,"240,000,000 [35]",JavaScript,PHP[36],MariaDB[37],Website manager software.
15,Netflix,"223.090.000 (Subscribers, not visitors)",JavaScript,"Python, Java[38]","NMDB,[39] PostgreSQL",The biggest video streaming service in the world.

In [5]:
df = df.drop([15,14,7,4])

In [6]:
df

,Websites,Popularity (unique visitors per month)[1],Front-end (Client-side),Back-end (Server-side),Database,Notes
0,Google[2],2800000000,"JavaScript, TypeScript","C, C++, Go,[3] Java, Python, Node","Bigtable,[4] MariaDB[5]",The most used search engine in the world.
1,Facebook,1120000000,"JavaScript, Typescript, Flow","Hack/HHVM, Python, C++, Java, Erlang, D,[6] Ha...","MariaDB, MySQL,[8] HBase, Cassandra[9]",The most visited social networking site.
2,YouTube,1100000000,"JavaScript, TypeScript","Python, C, C++, Java,[10] Go[11]","Vitess, BigTable, MariaDB[5][12]",The most popular video sharing site.
3,Yahoo,750000000,JavaScript,PHP,"PostgreSQL, HBase, Cassandra, MongoDB,[13]",NaN
5,Amazon,"2,400,000,000[18]",JavaScript,"Java, C++, Perl[19]","DynamoDB, RDS/Aurora, Redshift[20]",The most used e-commerce site in the world.
6,Wikipedia,475000000,JavaScript,PHP,MariaDB[21],"A free online encyclopedia based on MediaWiki,..."
8,Twitter,290000000,JavaScript,"C++, Java,[23] Scala,[24] Ruby (Ruby On Rails)",MySQL[25],Popular social network.
9,Bing,285000000,JavaScript,"C++, C#","Microsoft SQL Server, Cosmos DB",Search engine from Microsoft.
10,eBay,285000000,JavaScript,"Java,[26] JavaScript,[27] Scala[28]",Oracle Database,Online auction house.
11,MSN,280000000,JavaScript,C# (ASP.NET),Microsoft SQL Server,"An email client, for simple use. Previously kn..."
12,LinkedIn,260000000,JavaScript,"Java, JavaScript,[29] Scala",Venice[30][31],World's largest professional network.
13,Pinterest,250000000,JavaScript,"Python (Django),[32] Erlang, Elixir[33]","MySQL, Redis[34]",Search engine for ideas.

In [7]:
df = df.drop(5)

In [8]:
df

,Websites,Popularity (unique visitors per month)[1],Front-end (Client-side),Back-end (Server-side),Database,Notes
0,Google[2],2800000000,"JavaScript, TypeScript","C, C++, Go,[3] Java, Python, Node","Bigtable,[4] MariaDB[5]",The most used search engine in the world.
1,Facebook,1120000000,"JavaScript, Typescript, Flow","Hack/HHVM, Python, C++, Java, Erlang, D,[6] Ha...","MariaDB, MySQL,[8] HBase, Cassandra[9]",The most visited social networking site.
2,YouTube,1100000000,"JavaScript, TypeScript","Python, C, C++, Java,[10] Go[11]","Vitess, BigTable, MariaDB[5][12]",The most popular video sharing site.
3,Yahoo,750000000,JavaScript,PHP,"PostgreSQL, HBase, Cassandra, MongoDB,[13]",NaN
6,Wikipedia,475000000,JavaScript,PHP,MariaDB[21],"A free online encyclopedia based on MediaWiki,..."
8,Twitter,290000000,JavaScript,"C++, Java,[23] Scala,[24] Ruby (Ruby On Rails)",MySQL[25],Popular social network.
9,Bing,285000000,JavaScript,"C++, C#","Microsoft SQL Server, Cosmos DB",Search engine from Microsoft.
10,eBay,285000000,JavaScript,"Java,[26] JavaScript,[27] Scala[28]",Oracle Database,Online auction house.
11,MSN,280000000,JavaScript,C# (ASP.NET),Microsoft SQL Server,"An email client, for simple use. Previously kn..."
12,LinkedIn,260000000,JavaScript,"Java, JavaScript,[29] Scala",Venice[30][31],World's largest professional network.
13,Pinterest,250000000,JavaScript,"Python (Django),[32] Erlang, Elixir[33]","MySQL, Redis[34]",Search engine for ideas.

In [9]:
df = df.rename(columns = {'Popularity (unique visitors per month)[1]':'Popularity'
                         ,'Front-end (Client-side)':'Front_end'
                         ,'Back-end(Server-side)':'back_end'})

In [11]:
conn = pg2.connect(host = "localhost",port = 5432 , dbname="Programming_language", user="postgres", password = "hamzaowais1")

In [19]:
from sqlalchemy import create_engine

In [20]:
engine = create_engine('postgresql+psycopg2://postgres:hamzaowais1@localhost:5432/Programming_language')

In [25]:
df.to_sql('popular_languages',engine, if_exists='replace', index = False)

11